import { readFile } from "fs/promises";
import path from "path";

// ────────────────────────────────────────────────────────────────
// GET /api/files/[name]
//
// Serves files from the /uploads directory.
// Used to serve the HTML reports generated by JR's model.
// e.g. /api/files/a1b2c3d4_report.html → opens the DFM report
// ────────────────────────────────────────────────────────────────

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ name: string }> }
) {
  const { name } = await params;

  // Basic safety — no path traversal
  if (!name || name.includes("..") || name.includes("/") || name.includes("\\")) {
    return new Response("Bad file name", { status: 400 });
  }

  const filePath = path.join(process.cwd(), "uploads", name);

  try {
    const buf = await readFile(filePath);

    // Content type based on extension
    const lower = name.toLowerCase();
    let contentType = "application/octet-stream";
    if (lower.endsWith(".html")) contentType = "text/html";
    else if (lower.endsWith(".pdf")) contentType = "application/pdf";
    else if (lower.endsWith(".step") || lower.endsWith(".stp")) contentType = "application/octet-stream";

    // HTML reports should render in browser, not download
    const disposition = lower.endsWith(".html") ? "inline" : `attachment; filename="${name}"`;

    return new Response(buf, {
      headers: {
        "content-type": contentType,
        "content-disposition": disposition,
      },
    });
  } catch {
    return new Response("Not found", { status: 404 });
  }
}